### ISSUE TITLE
Not sure why you've given paragraphs ids?

### ISSUE THREAD

**Issue by drgrigg** [DavidMGross/cicero-tusculan-disputations-c-d-yonge#1]
`<p id="p-1">` `<p id="p-2">` etc. Am I missing something? Is there a need for these? They don't seem to be targeted anywhere.

**Comment by drgrigg** [comment]
Similarly ids in table rows? `<tr id="p=5">` etc?

**Comment by davgross** [comment]
If you look at the original book, some of the paragraphs are labeled with ascending roman numerals. The author doesn't reference these numbers anywhere, so I'm not sure what they're for. I'm guessing they have something to do with divisions in the original Latin text. I considered making those numbers sub-heads for sections, but instead decided to omit them.  I kept those ids in the markup just in case there might be a cause to refer to one of the numbers (e.g. if there was a footnote that said "as Cicero noted in section IV, ...") but that didn't happen. The ids don't serve a function now, but they also don't do any harm, so I let them be. Maybe someone who recycles the HTML for a webpage some day will be glad they're there.

**Comment by drgrigg** [comment]
Thanks. I'm also just now reading your Production Notes in content.opf. I should have done that first.

**Comment by drgrigg** [comment]
OK, maybe leave them then.

**Comment by drgrigg** [comment]
But might get @acabal to comment

**Comment by acabal** [comment]
If ids aren't used, we should remove them. Thanks!
