### ISSUE TITLE
Lint error f-004: core.css does not match template?

### ISSUE THREAD

**Issue by drgrigg** [DavidMGross/cicero-tusculan-disputations-c-d-yonge#2]
This may be due to changes in the latest toolset (either on your machine or mine)?

**Comment by davgross** [comment]
Hmmm... doesn't happen when I lint, so probably so.

**Comment by drgrigg** [comment]
Looks like there's an added line in the most recent core.css (I installed the new toolset just this morning). Starting line 98 of core.css:

```
a[epub|type~="noteref"]{
	font-size: .75em;
	font-style: normal !important;
	vertical-align: super;
}
```

The font-style line is new.

**Comment by davgross** [comment]
Could you push that change in a PR, or would you like me to do it at my end?

**Comment by drgrigg** [comment]
I'm saying that I think Alex has made this change in the latest toolset 1.2.4

**Comment by drgrigg** [comment]
So you can just make the change in your copy of core.css
