### ISSUE TITLE
Visual appearance: dialog tables seem to need more space at the start

### ISSUE THREAD

**Issue by drgrigg** [DavidMGross/cicero-tusculan-disputations-c-d-yonge#3]
In the compiled epub, it looks to my eye as though there needs to be more space between the normal text and the beginning of the `<table>` sections. 

I'm not sure if this ought not to be a standard thing in our CSS, to be honest, just a 1em margin-top for `<table>`? Alex might need to comment on this.

**Comment by davgross** [comment]
I agree, and I think you're right that this probably belongs in the core css.

**Comment by drgrigg** [comment]
@acabal can you comment?

**Comment by acabal** [comment]
1em margin for tables is good. 1em in general is the basic step of margins whenever necessary.

We prefer to keep core.css very generic, as hopefully user agents will have their own base styles, and we don't want to include a lot of default CSS for elements that might not appear in every ebook. So, let's leave it out of core.css for now.
